title: Reactive World
theme: jekyll-theme-midnight
description: > # this means to ignore newlines until "baseurl:"
 Site about reactive programming world. It contains some basics about Reactive Programming and Functional Reactive programming. Also information how to use ReactiveX. 
baseurl: "/"
url: "https://reactiveworld.net"
twitter_username: rosprog
github_username:  novros
email: novros@reactiveworld.net

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap

# Paginator
paginate: 5
paginate_path: "/posts/page:num/"

# Build settings
markdown: kramdown
include: ['_pages']
kramdown:
  input: GFM
encoding: UTF-8

